config/routes.rb
Issues::Application.routes.draw do
  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login" => "user_sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :user_sessions
  get "secret" => "home#secret", :as => "secret"

  get "pages/home", :as => "home"

  get "pages/about", :as => "about"

  get "pages/help", :as => "help"

  resources :issues

  resources :categories
  
  resources :password_resets
  
  root to: 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :issues
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :category_id, :description, :issue_id, :subject
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :password_confirmation
  
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
  def not_authenticated
    redirect_to root_path, :alert => "Please login first."
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :require_login
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login
    
  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by_email(params[:email])
        
    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user
        
    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end
    
  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated unless @user
  end
      
  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token(params[:token])
    not_authenticated unless @user
    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = login(params[:username], params[:password], params[:remember_me])
    if user
      redirect_back_or_to issues_path, notice: "Logged in!"
    else
      flash.now.alert = "Username or password invalid"
    end
  end
  
  def destroy
    logout
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
     user = login(params[:username], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_path, notice: "Logged in!"
    else
      flash.now.alert = "Username or password invalid"
    end
  end
    
  def destroy
    logout
    redirect_to(root_path, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_path, notice: "You are now registered!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category, class: "btn" %></td>
    <td><%= link_to 'Edit', edit_category_path(category), class: "btn" %></td>
    <td><%= link_to 'Destroy', category, class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path, class: "btn" %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category), class: "btn" %> |
<%= link_to 'Back', categories_path, class: "btn" %> |
<%= link_to 'New Category', new_category_path, class: "btn" %>

app/views/issues/_form.html.erb
<%= simple_form_for(@issue) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :issue_id %>
    <%= f.input :subject %>
    <%= f.association :category %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1>Listing issues</h1>

<table class="table table-striped">
  <tr>
    <th>Issue</th>
    <th>Subject</th>
    <th>Category</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.issue_id %></td>
    <td><%= issue.subject %></td>
    <td><%= issue.category_id %></td>
    <td><%= issue.description %></td>
    <td><%= link_to 'Show', issue, class: "btn" %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue), class: "btn" %></td>
    <td><%= link_to 'Destroy', issue, class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path, class: "btn" %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issue:</b>
  <%= @issue.issue_id %>
</p>

<p>
  <b>Subject:</b>
  <%= @issue.subject %>
</p>

<p>
  <b>Category:</b>
  <%= @issue.category_id %>
</p>

<p>
  <b>Description:</b>
  <%= @issue.description %>
</p>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= params[:controller] %>">
    <header class="navbar navbar-fixed-top">
    	<a class="brand" href="home">
		  Project name
		</a>
		<nav class="navbar-inner">
         <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Issues", issues_path %></li>
        </ul>
        <form class="navbar-search pull-left">
		  <input type="text" class="search-query" placeholder="Search">
		</form>
		<ul class="nav pull-right">
		 <div id="container">
		    <div class="user_nav">
		      <% if current_user %>
		        Logged in as <%= current_user.username %>
		        <%= link_to "Log out", logout_path, class: "btn" %>
		      <% else %>
		        <%= link_to "Sign up", signup_path, class: "btn" %> or
		        <%= link_to "Log in", login_path, class: "btn"  %>
		      <% end %>
		    </div>
		    <% flash.each do |name, msg| %>
		      <%= content_tag :div, msg, :id => "flash_#{name}" %>
		    <% end %>
		  </div>
		</ul>
      </div>
      </nav>
    </header>
    <div class="span10 offset1">
    	<% flash.each do |key, value| %>
					<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>			
    </div>
	    
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span9">  <%= yield %> </div>
            	
            
              
              <div class="span3">
		    	 <h2>Placeholder</h2>
		     	 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
		  	  
            	</div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome!</h1>
<p>This system is for tracking issues and their resolutions.</p>

<p>To start using this system please signup by clicking the "Sign up" button at the top right of the screen or by clicking the button below</p>


<%= link_to "Sign up!", signup_path, class: "btn btn-large" %>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
	    
	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	    
	  <div class="field">
	    <%= f.label :email %><br />
	    <%= @user.email %>
	  </div>
	  <div class="field">
	    <%= f.label :password %><br />
	    <%= f.password_field :password %>
	  </div>
	  <div class="field">
	    <%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation %>
	    <%= hidden_field_tag :token, @token %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/user_sessions/_form.html.erb
<form class="form-inline">
<%= form_tag user_sessions_path, :method => :post do %>
  
  <div class="field-inputs">
    <%= label_tag :username %><br />
    <%= text_field_tag :username %>
  </div>
  <div class="field-inputs">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
    <%= label_tag :remember_me %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", class: "btn btn-primary" %>
  </div>
<% end %>

</form>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<br>
</br>
<%= render 'form' %>

<%= link_to 'Back', user_sessions_path, class: "btn" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<br>
<br/>
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, label: "Register" %>
  </div>
<% end %>